#!/usr/bin/env python

import sys
import os
import subprocess

if len(sys.argv) < 2 :
    sys.exit(1)

module_name = sys.argv[1];

cmdline = 'git submodule deinit -f ' + ' ./vim/.vim/bundle/' + module_name
print cmdline
subprocess.call(cmdline.split())

cmdline = 'git rm -f ' + ' ./vim/.vim/bundle/' + module_name
print cmdline
subprocess.call(cmdline.split())
