#!/usr/bin/env python

from urlparse import urlparse
import sys
import os
import subprocess

def invoke(cmdline) :
	print cmdline
	subprocess.call(cmdline.split())

invoke('git sudmobule status')
invoke('git pull --rebase')
invoke('git submodule update --init --recursive')
invoke('git submodule foreach git pull origin master')
invoke('git sudmobule status')

